services:
  - type: web
    name: garka-backend
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    rootDirectory: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: MONNIFY_SANDBOX
        value: "false"
      - key: MONNIFY_AUTO_PAYOUT
        value: "true"
      - key: PLATFORM_COMMISSION
        value: "0.1"
      - key: ADMIN_COMMISSION
        value: "0.05"
